"""delete post_votes

Revision ID: 1488d62dcd68
Revises: f34a5d703adc
Create Date: 2025-10-19 23:28:49.873948

"""

from typing import Sequence, Union


# revision identifiers, used by Alembic.
revision: str = "1488d62dcd68"
down_revision: Union[str, Sequence[str], None] = "f34a5d703adc"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
