"""add thread votes table

Revision ID: e32818e21205
Revises: fdddacb790a5
Create Date: 2026-01-13 19:43:38.291642

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "e32818e21205"
down_revision: Union[str, Sequence[str], None] = "fdddacb790a5"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "thread_votes",
        sa.Column("thread_sid", sa.UUID(), nullable=False, comment="Thread ID"),
        sa.Column("user_sid", sa.UUID(), nullable=False, comment="User ID"),
        sa.Column(
            "value", sa.Integer(), nullable=False, comment="Value of thread votes"
        ),
        sa.Column("sid", sa.UUID(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.CheckConstraint("value IN (-1, 1)", name="check_vote_value_valid"),
        sa.ForeignKeyConstraint(
            ["thread_sid"], ["threads.threads.sid"], ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(["user_sid"], ["users.users.sid"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("sid"),
        sa.UniqueConstraint("sid"),
        sa.UniqueConstraint("thread_sid", "user_sid", name="uq_thread_vote_user"),
        schema="threads",
        comment="Post Votes table",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("thread_votes", schema="threads")
    # ### end Alembic commands ###
